services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
  postgres:
    image: postgres
    container_name: local_postgre
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: postgres

